language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - "3.7-dev"

# install dependencies
install:
  - pip install -r requirements/dev.txt
  - pip install codecov

# run scripts
script:
  - python -m unitest discover
  - coverage report webapp.py
  - pylint --output-format=html wepapp.py > pylint_report.html


after_success:
  - codecov