language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - "3.7-dev"

# install dependencies
install:
  - pip install -r requirements/dev.txt
  - pip install codecov

# run scripts
script:
  - python -m unittest discover
  - coverage html
  # - pylint --output-format=html webapp.py > pylint_report.html


after_success:
  - codecov