language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - "3.7-dev"

# install dependencies
install:
  - pip install -r requirements/dev.txt
  - pip install coveralls

# run scripts
script:
  - coverage run test_webapp.py
  -  pylint --output-format=html src > pylint_report.html


after_success:
  - codecov